# Generated by Django 5.2.1 on 2025-06-11 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0003_student_dateofbirth_student_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmark',
            name='average',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='term',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
