# Generated by Django 5.2.1 on 2025-06-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0004_remove_studentmark_average_alter_assignment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='average',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='ExamMark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='courseMark',
            field=models.FloatField(default=1),
        ),
    ]
