# Generated by Django 5.2.1 on 2025-08-03 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0005_studentmark_average_alter_studentmark_exammark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentTrack.classroom'),
        ),
    ]
