# Generated by Django 5.2.1 on 2025-08-09 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0006_alter_student_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksDistribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.JSONField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentTrack.assignment')),
            ],
        ),
    ]
