# Generated by Django 5.2.1 on 2025-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0007_marksdistribtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marksdistribtion',
            name='distribution',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
