# Generated by Django 5.2.1 on 2025-08-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0008_alter_marksdistribtion_distribution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarksDistribtion',
            new_name='MarksDistribution',
        ),
    ]
