# Generated by Django 5.2.1 on 2025-08-11 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0009_rename_marksdistribtion_marksdistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentTrack.subject'),
        ),
    ]
