# Generated by Django 5.2.1 on 2025-08-20 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0010_alter_studentmark_learner_alter_studentmark_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='educator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentTrack.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
