# Generated by Django 5.2.5 on 2025-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentTrack', '0011_alter_subject_educator_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
